name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "17 18 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.13"
      - name: Compile Python sources
        run: python -m compileall -q custom_components

  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa
        with:
          category: integration
          ignore: brands

  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb
